# Generated by Django 4.0.3 on 2024-02-13 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders_App', '0002_alter_ordereddish_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereddish',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Date'),
        ),
    ]
